name = "archivepronto"
main = "worker.js"
workers_dev = true
compatibility_date = "2025-08-30"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
GITHUB_OWNER = "nikovlod"
GITHUB_REPO = "archivepronto"

[triggers]
# This runs the scheduled task at the start of every hour.
crons = ["0 * * * *"]
